### ISSUE TITLE
Support RIS as output format

### ISSUE THREAD

**Issue by zuphilip** [larsgw/citation.js#125]
This is a feature request to support [RIS](https://en.wikipedia.org/wiki/RIS_(file_format)) as an output format. It was first mentioned here https://github.com/rmzelle/ref-extractor/pull/22#issuecomment-354700787 . RIS is another standard bibliographic format which most reference management software understand. Moreover, the [publish or perish](https://harzing.com/resources/publish-or-perish) tool can import from RIS but not from BibTeX and also the [VOS viewer](http://www.vosviewer.com/) can import RIS data.

**Comment by larsgw** [comment]
I'm creating mappings now (here's the [spreadsheet](https://docs.google.com/spreadsheets/d/1Yp1nooP35K3A4o_dKhTIqa9cksSam6LtYsBm4MQlJIo/edit?usp=sharing)), and I have some questions regarding some of those. I've only looked at the lists on Wikipedia and the Zotero translator as of writing. Of course, other comments are welcome as well!

## Types

- [ ] `paper-conference`: is `CONF` (Zotero) preferable to `CPAPER` (Wikipedia)?
- [ ] is `HEAR` ("Hearing") appropriate for `interview`?
- [ ] is `ICOMM` ("Internet Communication") appropriate for `post`?
- [ ] `article-journal`: `JFULL` or `JOUR`?
- [ ] `article`: same as `article-journal`, or something else?
- [ ] is `ADVS` ("Audiovisual material") **or something else** appropriate for `broadcast`? (Otherwise `GEN` ("Generic"))
- [ ] is `CTLG` ("Catalog") **or something else**  appropriate for `entry`? (Otherwise `GEN` ("Generic"))
- [ ] is there **anything** appropriate for`review`, `review-book` and `treaty` (Otherwise `GEN` ("Generic"))
- [ ] Currently unmapped RIS types that aren't under consideration for anything: ABST, AGGR, ANCIENT, CHAR, CLSWK, COMP, DBASE, EBOOK, ECHAP, EDBOOK, EJOUR, EQUA, GOVDOC, GRANT, INPR, MULTI, SER, SLIDE, STAND, STAT, UNPB, VIDEO. I might have missed some appropriate CSL types, so if there are any, please notify.

## Fields

- A lot of questions, see the spreadsheet. The Zotero mappings do a lot of weird things, like mapping `number-of-volumes` to `IS` ("Issue number"), which seems weird to me, but if that's the way it's used, then fine.
- Also, authors and title tags will be annoying.

**Comment by larsgw** [comment]
I've pushed a prototype version to master, feedback is welcome.

**Comment by zuphilip** [comment]
Cool! Thank you! I try to look at, but can't promise any time... CC @rmzelle

**Comment by rmzelle** [comment]
@larsgw, I enabled RIS output at https://rintze.zelle.me/ref-extractor/, and it seems to work fine with 0.4.0-7, but I'm seeing the following error in my browser console:

> [get] Option style ("ris") should be one of: csl,bibtex,bibtxt,citation-* citation.min.js:1:521657 

I'm using the invocation

```js
  var Cite = require('citation-js');
  var cite = new Cite();
  ...
  cite.set(csl_json);
  
  cite.get({
    type: "string",
    style: "ris"
  });
```

Is this just overzealous validation? See also https://github.com/larsgw/citation.js/blob/6e87edde1be0adaa40ee0da6aa45ef73d9e36408/src/Cite/static.js#L3 which is missing "ris" as an option.

**Comment by rmzelle** [comment]
("ris" is still missing at https://citation.js.org/api/tutorial-output_options.html too)

**Comment by larsgw** [comment]
In `v0.4.0-1` I introduced a new API for formatting output, and deprecated the old one. Therefore, the old api (`Cite#get()`) didn't get any of the updates (i.e. RIS, citation support next to bibliography support and the Software Formats plugin), and it isn't planned to get any new ones either. The new API (`Cite#format()`) is documented [here](https://github.com/larsgw/citation.js/blob/master/docs/cite_output.md), with extensive option documentation [here](https://github.com/larsgw/citation.js/blob/master/docs/output_formats.md). Feedback is welcome.

I'm planning to create a `v0.3`-to-`v0.4` migration guide, which will include these changes.
